sudo: false
language: node_js

node_js:
  - "6.8.1"
  - "6.9.1"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export JOBS=max
  - export prebuild_compile=true